### ISSUE TITLE
Better normal for general parametric bodies

### ISSUE THREAD

**Issue by marinlauber** [WaterLily-jl/ParametricBodies.jl#6]
We need to define a more general normal vector for parametric bodies. The rest carries nicely from 2D to 3D but not those lines.

https://github.com/weymouth/ParametricBodies.jl/blob/48e49e990d7a47f72289f90f74c2f15f64f00b3b/src/ParametricBodies.jl#L99C1-L102C4

**Comment by weymouth** [comment]
Is this fixed with 0.2?

**Comment by marinlauber** [comment]
Yes, this is fixed. I will close it.
