### ISSUE TITLE
norm_dir returns [0,0] when uv is on the lims of the curve parameter

### ISSUE THREAD

**Issue by marinlauber** [WaterLily-jl/ParametricBodies.jl#9]
https://github.com/weymouth/ParametricBodies.jl/blob/9e78f08be2c28aabf74a105753b71ac8e7cc8fac/src/ParametricBodies.jl#L104C1-L107C4

This is annoying as it results in a division by zero for the normal vector computation and pollutes the distance field. Luckily it doesn't occur very often and the fix seems simple enough `lims = clamp.(lims,lims[1]+eps(T),lims[2]-eps(T))` and clamping any uv to these limits ensure that the normal is always a vector with non-zero magnitude.

**Comment by weymouth** [comment]
I think this is fixed. Can you check your use case?
